### PR TITLE
`export: Command not found` on mac

### PR DESCRIPTION
**Pull request by jayenashar**

### CODE REVIEW

**Comment by Gnito** [comment]
@jayenashar, this sounds pretty strange, since we actually develop this on macs.
Have you started to use some exotic _shell_ that doesn't support `export`? 
(I think most of us use zsh, but maybe even bash shell is still used.)

Anyway, we are probably going in this direction:
https://github.com/sharetribe/ftw-daily/pull/1555

**Comment by jayenashar** [comment]
yeah great.  i had a call with aleksi and showed him the issue and i also suggested using cross-env.  i'll close this PR.

**Comment by jayenashar** [comment]
it's not my machine but no exotic shell was in use.  `export` works fine on the command line but not when invoked from `npm run` or `yarn run`

**Comment by Gnito** [comment]
Ah, right!

You could maybe check your npm configs:
`npm config ls -l | grep shell`

or _yarn_ might also have some script shell config set.

**Comment by jayenashar** [comment]
`npm config ls -l | grep shell` gives /bin/bash

**Pull request closed without merging**
